#!/bin/bash

# Set workdir
WORKDIR=$(pwd)

log_info() {
    echo -e "\033[34m[INFO]\033[0m $1"
}

create_konsole_tab() {
    COMMAND=$1
    konsole --noclose --show-tabbar --new-tab --workdir "$WORKDIR" -e $SHELL -c "$COMMAND; $SHELL"
}

identify_web_ports() {
    nmap_output="$1"
    excluded_ports="5357,5985,593,47001,49674"
    web_ports=()

    while IFS= read -r line; do
        if [[ "$line" =~ (http|ssl/http) ]]; then
            port=$(echo "$line" | grep -oP '^\d+/tcp' | cut -d '/' -f 1)
            if ! echo "$excluded_ports" | grep -q "$port"; then
                web_ports+=("$port")
            fi
        fi
    done <<< "$nmap_output"

    echo "${web_ports[@]}"
}

feroxbuster_brute_force() {
    target="$1"
    web_ports="$2"
    feroxbuster_directory="$target/feroxbuster"
    wordlist="/usr/share/wordlists/seclists/Discovery/Web-Content/directory-list-2.3-medium.txt"
    
    # Ensure the feroxbuster directory exists
    mkdir -p "$feroxbuster_directory"
    
    for port in $(echo "$web_ports" | tr ',' '\n'); do
        log_info "Running Feroxbuster on target: $target, port: $port"
        feroxbuster --no-state --url "http://$target:$port" --wordlist "$wordlist" --output "$feroxbuster_directory/$port.txt" --depth 4 --threads 40 --auto-tune --extract-links --insecure --extensions "html,htm,php,asp,aspx,jsp" --filter-status "404,405,503,502,411,403,501,400" --methods "GET,POST,PUT" --filter-size 0 --filter-words 0
    done
}

main() {
    target="$1"
    nmap_directory="$target/nmap"
    
    # Ensure the nmap directory exists
    mkdir -p "$nmap_directory"
    
    # Step 1: Run the initial Nmap scan to find open ports
    log_info "Running initial Nmap scan on target: $target"
    open_ports=$(sudo nmap -p- --min-rate=1000 -T4 "$target" | grep ^[0-9] | cut -d '/' -f 1 | tr '\n' ',' | sed 's/,$//')
    
    if [ -z "$open_ports" ]; then
        log_info "No open ports found."
        return
    fi
    
    log_info "Detected open ports: $open_ports"
    
    # Step 2: Run the detailed Nmap scan on the detected open ports in a new Konsole tab
    detailed_nmap_command="sudo nmap -sC -sV --version-all -O -p$open_ports -vvv $target"
    create_konsole_tab "$detailed_nmap_command"
    
    # Step 3: Run the command to identify web ports in the current terminal
    detailed_nmap_output=$(sudo nmap -sC -sV --version-all -O -p"$open_ports" -vvv "$target")
    web_ports=$(identify_web_ports "$detailed_nmap_output")
    log_info "Identified web server ports (excluding certain ports): $web_ports"
    
    # Step 4: Display the results and run feroxbuster on the identified web server ports  in a new Konsole tab
    display_command="echo \"$detailed_nmap_output\"; echo \"Identified web server ports (excluding certain ports): $web_ports\"; $(declare -f feroxbuster_brute_force); feroxbuster_brute_force $target \"$web_ports\""
    create_konsole_tab "$display_command"
}

main "$@"
